USE careflow;

-- Password for all sample users: Password@123
-- Hashes can be replaced with values generated by utils.auth.hash_password().

INSERT INTO users (email, password_hash, full_name, role, session_token)
VALUES
('patient1@example.com', 'scrypt:32768:8:1$hJHNlkuEierbtxy3$aeab79b3d19d12a32711100e13612fcbb5357b205d8f0f1586bda11d0f586ac44c43e5628f8e6fcdfc43ba02c116604f000bb4c7f4f8c05ef10bd751e3336212', 'Aarav Sharma', 'patient', 'patient-token-123'),
('patient2@example.com', 'scrypt:32768:8:1$hJHNlkuEierbtxy3$aeab79b3d19d12a32711100e13612fcbb5357b205d8f0f1586bda11d0f586ac44c43e5628f8e6fcdfc43ba02c116604f000bb4c7f4f8c05ef10bd751e3336212', 'Meera Iyer', 'patient', 'patient-token-456'),
('doctor1@example.com', 'scrypt:32768:8:1$hJHNlkuEierbtxy3$aeab79b3d19d12a32711100e13612fcbb5357b205d8f0f1586bda11d0f586ac44c43e5628f8e6fcdfc43ba02c116604f000bb4c7f4f8c05ef10bd751e3336212', 'Dr. Kavya Rao', 'doctor', 'doctor-token-123'),
('doctor2@example.com', 'scrypt:32768:8:1$hJHNlkuEierbtxy3$aeab79b3d19d12a32711100e13612fcbb5357b205d8f0f1586bda11d0f586ac44c43e5628f8e6fcdfc43ba02c116604f000bb4c7f4f8c05ef10bd751e3336212', 'Dr. Arjun Menon', 'doctor', 'doctor-token-456');

INSERT INTO doctors (user_id, specialty, room_number)
VALUES
((SELECT id FROM users WHERE email = 'doctor1@example.com'), 'Cardiology', 'A101'),
((SELECT id FROM users WHERE email = 'doctor2@example.com'), 'Orthopedics', 'B205');

INSERT INTO appointments (
    patient_id,
    doctor_id,
    appointment_date,
    time_slot,
    queue_number,
    status
)
VALUES
(
    (SELECT id FROM users WHERE email = 'patient1@example.com'),
    (SELECT doctors.id FROM doctors JOIN users ON doctors.user_id = users.id WHERE users.email = 'doctor1@example.com'),
    CURDATE(),
    '10:00:00',
    1,
    'scheduled'
),
(
    (SELECT id FROM users WHERE email = 'patient2@example.com'),
    (SELECT doctors.id FROM doctors JOIN users ON doctors.user_id = users.id WHERE users.email = 'doctor1@example.com'),
    CURDATE(),
    '10:15:00',
    2,
    'scheduled'
);
